### ISSUE TITLE
Obsolete documentation in HOMEPAGE

### ISSUE THREAD

**Issue by l29ah** [gentoo-haskell/haskell-updater#10]
It leads to http://haskell.org/haskellwiki/Gentoo#haskell-updater that leads to 404 darcs repo.

**Comment by hololeap** [comment]
https://github.com/gentoo-haskell/haskell-updater/blob/3157ba41ea1793f844218a87b32bcc9f041c028b/haskell-updater.cabal#L2

Shouldn't we just link it to `https://github.com/gentoo-haskell/haskell-updater#readme`?
