### ISSUE TITLE
`haskell-updater` doesn't work with `ghc-9.4`

### ISSUE THREAD

**Issue by hololeap** [gentoo-haskell/haskell-updater#20]
Hadrian rearranges things a bit. Instead of the previous directory structure:

```console
$ ls /usr/lib64/ghc-9.2.7/
bin
package.conf.d
...
```

The new one looks like:

```console
$ ls /usr/lib64/ghc-9.4.4/
bin
lib
```

Moreover, the reported library directory has changed:

```console
$ /usr/bin/ghc --print-libdir
/usr/lib64/ghc-9.4.4/lib
```

Something about this change seems to be confusing `haskell-updater`, which thinks all installed packages are outdated, no matter what.

_Originally posted by @hololeap in https://github.com/gentoo-haskell/gentoo-haskell/issues/1397#issuecomment-1518285434_

**Comment by markwright** [comment]
This hack seems to help:
```
--- haskell-updater-1.3.2-orig/Distribution/Gentoo/GHC.hs	1970-01-01 10:00:00.000000000 +1000
+++ haskell-updater-1.3.2/Distribution/Gentoo/GHC.hs	2023-06-23 00:09:16.946784086 +1000
@@ -235,8 +235,10 @@
 
     isValid dir = any (`isGhcLibDir` dir) libDirs
 
+    thisGhc' = if BS.isSuffixOf (BS.pack "/lib") thisGhc then BS.dropEnd 4 thisGhc else thisGhc
+
     -- Invalid if it's this GHC
-    isInvalid fp = fp == thisGhc || BS.isPrefixOf (thisGhc `BS.snoc` pathSeparator) fp
+    isInvalid fp = fp == thisGhc' || BS.isPrefixOf (thisGhc' `BS.snoc` pathSeparator) fp
 
 -- A valid GHC library directory starting at libdir has a name of
 -- "ghc", then a hyphen and then a version number.
```

**Comment by hololeap** [comment]
I wonder if patching `hadrian` so that it keeps the old behavior would be a better idea.

**Comment by markwright** [comment]
The hack in my previous comment seems to work upgrading from ghc-9.2.7 to ghc-9.4.5 and rebuilding broken packages with ghc-9.4.5. If anyone wants to try it, the patch can be saved as:
/etc/portage/patches/app-admin/haskell-updater-1.3.2/haskell-updater-1.3.2-ghc-9.4.patch
However I have not tested it yet upgrading from ghc-9.4.5 to a newer version, so it might be broken in this scenario.
I'm unsure what we should do. Patching hadrian would mean we have to maintain this patch, which we normally try to avoid.

**Comment by hololeap** [comment]
I asked in `#ghc` and it sounds like the option of patching hadrian isn't really on the table, so we'll just have to modify things on our side to work with the new directory structure.

**Comment by hololeap** [comment]
Thanks for adding that in, @l29ah
