### ISSUE TITLE
haddock should be updated first?

### ISSUE THREAD

**Issue by Javran** [gentoo-haskell/haskell-updater#3]
I was upgrading to the newest haskell platform, and some haskell packages failed to build.
Then I used haskell-updater to fix the problem. However, when it figured out the broken packages and called emerge, it still failed to build due to the inconsistency of haddock internal GHC version number.

My build log can be found [here](https://gist.github.com/Javran/c0f1b15d0d6c86e3992c#file-gistfile1-txt-L105).

Despite that haddock did appear in the long command line generated by haskell-updater, it wasn't the first to be emerged. If I manually emerge haddock first, then everything works fine.

**Comment by trofi** [comment]
Starting with ghc-7.10 we now use haddock bundled with ghc (which means haddock always works).
